<?php

namespace Page\SaleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategogyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategogyRepository extends EntityRepository
{
}
