<?php

namespace Page\SaleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewRepository extends EntityRepository
{
}
