_selection:
    pattern:  /admin
    defaults: { _controller: PageSaleBundle:Admin:index }
_ckediter:
    pattern:  /bundles/pagesale/ckfinder/ckfinder/
    #defaults: { _controller: AcmeFrancketFilsBundle:Admin:rendezvousdelete }